// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4MyvpiJLuPIb0MyYRYRo4TUiY61AvLNs',
    appId: '1:601885291014:web:a8ea0374b1a3bf0c380987',
    messagingSenderId: '601885291014',
    projectId: 'tfg-app-productivitat-adaptada',
    authDomain: 'tfg-app-productivitat-adaptada.firebaseapp.com',
    storageBucket: 'tfg-app-productivitat-adaptada.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDdNrrtvduY7jo69QWHp9WQ7KNNIQy2io',
    appId: '1:601885291014:android:ccfacc4b2717c261380987',
    messagingSenderId: '601885291014',
    projectId: 'tfg-app-productivitat-adaptada',
    storageBucket: 'tfg-app-productivitat-adaptada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHlyVhCFOmy-Rl3FqdYihc3gH5Gw0OFRU',
    appId: '1:601885291014:ios:4602ea997113d4df380987',
    messagingSenderId: '601885291014',
    projectId: 'tfg-app-productivitat-adaptada',
    storageBucket: 'tfg-app-productivitat-adaptada.firebasestorage.app',
    iosBundleId: 'com.example.aplicaciotempstfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHlyVhCFOmy-Rl3FqdYihc3gH5Gw0OFRU',
    appId: '1:601885291014:ios:4602ea997113d4df380987',
    messagingSenderId: '601885291014',
    projectId: 'tfg-app-productivitat-adaptada',
    storageBucket: 'tfg-app-productivitat-adaptada.firebasestorage.app',
    iosBundleId: 'com.example.aplicaciotempstfg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4MyvpiJLuPIb0MyYRYRo4TUiY61AvLNs',
    appId: '1:601885291014:web:92406810ee2e8dbe380987',
    messagingSenderId: '601885291014',
    projectId: 'tfg-app-productivitat-adaptada',
    authDomain: 'tfg-app-productivitat-adaptada.firebaseapp.com',
    storageBucket: 'tfg-app-productivitat-adaptada.firebasestorage.app',
  );
}
